services:
  app:
    image: teadark/geotrave:latest
    container_name: geotrave
    environment:
      POSTGIS_DSN: postgresql://geotrave:${DB_PASSWORD:-geotrave_dev}@geotrave-db:5432/geotrave
    volumes:
      - checkpoints:/app/database/checkpointer
      - ./.env:/app/.env:ro
    ports:
      - "8000:8000"
      - "8501:8501"
    restart: unless-stopped

volumes:
  checkpoints:
