"""
Centralized Pydantic Models for GeoTrave.

This module defines all the structured data models used for communication
between nodes and for output parsing from LLMs.

Parent Module: src.agent
Dependencies: pydantic
"""

from typing import List, Optional
from pydantic import BaseModel, Field

# ----------------- Router node -----------------

class RouterIntent(BaseModel):
    """
    Schema for classification of user intent by the Router node.
    """
    enum_intent: str = Field(
        ...,
        description="Intent type: `new_destination`, `update_preferences`, `chit_chat_or_malicious`, `confirm_and_plan`, `re_recommend`"
    )
    is_safe: bool = Field(
        ..., 
        description="Whether the input is safe (True) or malicious/irrelevant (False)."
    )

# ----------------- Analyzer node -----------------

class UserProfile(BaseModel):
    """Structured user travel profile and preferences."""
    destination: List[str] = Field(default_factory=list, description="List of destinations.")
    days: Optional[int] = Field(default=None, description="Number of days.")
    date: Optional[List[Optional[str]]] = Field(default=None, description="Departure and return dates [start, end].")
    people_count: Optional[int] = Field(default=1, description="Number of travelers.")
    budget_limit: Optional[int] = Field(default=0, description="Total budget limit.")
    
    accommodation: Optional[str] = Field(default=None, description="Accommodation preferences (e.g., 5-star, homestay).")
    dining: Optional[str] = Field(default=None, description="Dining preferences/restrictions.")
    transportation: Optional[str] = Field(default=None, description="Transportation preferences.")
    pace: Optional[str] = Field(default=None, description="Travel pace (e.g., leisure, fast-paced).")
    activities: List[str] = Field(default_factory=list, description="Specific activities or themes.")
    
    preferences: List[str] = Field(default_factory=list, description="General unstructured positive preferences.")
    avoidances: List[str] = Field(default_factory=list, description="Keywords user wants to avoid.")

class TravelInfo(BaseModel):
    """Structured response from the Analyzer node."""
    user_profile: UserProfile = Field(default_factory=UserProfile)
    needs_research: bool = Field(default=False, description="Whether search/research is needed.")
    reply: str = Field(..., description="The conversational response to the user.")

# ----------------- Researcher node -----------------

class ResearchPlan(BaseModel):
    """Execution plan generated by the Researcher node."""
    local_query: Optional[str] = Field(None, description="Keyword for local vector DB search.")
    web_queries: List[str] = Field(default_factory=list, description="Keywords for web search.")
    need_weather: bool = Field(default=False, description="Whether weather data is required.")
    need_api: List[str] = Field(default_factory=list, description="Additional APIs needed.")
