"""研究循环模型 — 子图内部通信与父图可见视图。"""

from typing import Any, Dict, List, Optional
from datetime import datetime
from pydantic import BaseModel, Field
from typing import Literal

from .domain import SearchTask


class ResearchResult(BaseModel):
    """统一信封，包裹每条工具结果后送入 Critic。

    不同工具返回异构形状（POI JSON、网页文本、爬虫输出），此信封将其归一化，
    使得 Critic 和 Hash 仅依赖本契约，不依赖具体工具的 schema。
    """
    tool_name: str = Field(..., description="Tool that produced this result")
    query: str = Field(..., description="Original query text or serialised parameters")
    content_type: Literal["json", "text", "html", "url_list"] = Field(
        ..., description="Shape of the content field"
    )
    content: Any = Field(..., description="Full original result (shape governed by content_type)")
    content_summary: str = Field(
        ...,
        description="Short summary (≤500 chars) for Critic LLM scoring; avoids token blow-up on long text"
    )
    dimension: str = Field(
        default="general",
        description="Research dimension from the originating SearchTask"
    )
    timestamp: str = Field(
        default_factory=lambda: datetime.now().isoformat(),
        description="ISO 8601 creation time"
    )


class CriticResult(BaseModel):
    """Critic Layer 2 (LLM) 在 Layer 1 (黑名单) 通后产出的单条评估结果。"""
    query: str = Field(..., description="Query text this evaluation corresponds to")
    tool_name: str = Field(
        default="",
        description="Tool that produced this result; echoed from ResearchResult, used by Hash to separate doc vs non-doc"
    )
    safety_tag: Literal["safe", "unsafe"] = Field(
        ..., description="Content safety verdict"
    )
    relevance_score: float = Field(
        ..., ge=0, le=100, description="How well the result answers the query"
    )
    utility_score: float = Field(
        ..., ge=0, le=100, description="How actionable the result is for travel planning"
    )
    rationale: str = Field(..., description="Scoring rationale in natural language")


class LoopSummary(BaseModel):
    """单轮 Research Loop 迭代的聚合统计。"""
    pass_count: int = Field(..., description="Number of results passing all three filter layers")
    total_count: int = Field(..., description="Total results evaluated this iteration")
    avg_relevance: float = Field(..., description="Mean relevance score across passed results")
    avg_utility: float = Field(..., description="Mean utility score across passed results")
    dimensions_covered: List[str] = Field(
        default_factory=list,
        description="Research dimensions covered by passed results"
    )


class ResearchLoopInternal(BaseModel):
    """子图私有状态。仅 Research Loop 节点读写这些字段。

    嵌套在 ResearchManifest.loop_state 中，父图只看到一个 key。
    外部节点（Manager、Reply、Recommender、Planner）严禁直接读写。
    """
    active_queries: List[SearchTask] = Field(
        default_factory=list,
        description="Search tasks generated by QG; Search node consumes then clears them"
    )
    query_results: Dict[str, Any] = Field(
        default_factory=dict,
        description="{{query_text: ResearchResult}} key-value pairs from the current iteration"
    )
    passed_results: List[CriticResult] = Field(
        default_factory=list, description="Results passing this iteration's filter"
    )
    all_passed_results: List[CriticResult] = Field(
        default_factory=list, description="Cumulative passed results across all iterations"
    )
    passed_queries: List[str] = Field(
        default_factory=list,
        description="Query texts that have already passed; QG must deduplicate against these"
    )
    feedback: Optional[str] = Field(
        default=None, description="Critic feedback for the next QueryGenerator iteration"
    )
    continue_loop: bool = Field(
        default=True, description="Critic decision: should the loop keep iterating?"
    )
    loop_iteration: int = Field(default=0, description="Current loop iteration count (0-indexed)")
    loop_summary: Optional[LoopSummary] = Field(
        default=None, description="Aggregated stats for the most recent iteration"
    )
    passed_doc_ids: List[str] = Field(
        default_factory=list,
        description="Document IDs accumulated across iterations; Search writes directly, Hash promotes to Manifest"
    )


class ResearchManifest(BaseModel):
    """存储在 TravelState.research_data 中的顶层研究状态模型。

    外部契约（Manager、Reply、Recommender、Planner 读取）:
        research_hashes  — {query: [hash_key, ...]} 映射
        research_history — 有序的 user_request 字符串列表

    内部契约（仅 Research Loop 子图节点读写）:
        loop_state       — ResearchLoopInternal（详见该类，含 active_queries 等子图私有字段）
    """
    research_hashes: Dict[str, List[str]] = Field(
        default_factory=dict,
        description="{{query_text: [hash_key, ...]}} — minimal global-state exposure"
    )
    loop_state: ResearchLoopInternal = Field(
        default_factory=ResearchLoopInternal,
        description="Subgraph-private state; external nodes must NOT touch"
    )
    research_history: List[str] = Field(
        default_factory=list,
        description="Ordered list of user_request strings; Manager uses last entry for freshness checks"
    )
    matched_doc_ids: List[str] = Field(
        default_factory=list,
        description="Document IDs matched this research session; stored in retrieval_db, separate from research_hashes"
    )
