# name: GeoTrave-base-test-CI (uv)

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       # 1. pull code
#       - name: Checkout code
#         uses: actions/checkout@v4

#       # 2. install uv
#       - name: Install uv
#         uses: astral-sh/setup-uv@v5
#         with:
#           enable-cache: true

#       # 3. set up Python
#       - name: Set up Python
#         run: uv python install

#       # 4. 安装项目依赖 (包含 dev 依赖如 pytest)
#       - name: Install dependencies
#         run: uv sync --frozen

#       # 5. 运行 Pytest
#       - name: Run tests
#         env:
#           OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#         run: uv run pytest